# Generated by Django 4.0.4 on 2022-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='goalamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
