# Generated by Django 4.0.4 on 2022-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_project_enddate_alter_project_funding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
